# The URL the site will be built for
base_url = "/"
title = "A Certain Scientific Impostor"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# # Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true

default_language = "en"

theme = "terminimal"

taxonomies = [
    {name = "tags"},
]

generate_feed = true
feed_filename = "rss.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"

smart_punctuation = true

[extra]
# Put all your custom variables here

logo_text = "Scientific Impostor"
author = "radical_subject"

# TODO: make footer less weird
copyright_html = "<div class=\"copyright\"><span>Â© 2021 radical_subject</span><span class=\"copyright-theme\"><span class=\"copyright-theme-sep\">:: </span>Theme is based on <a href=\"https://github.com/pawroman/zola-theme-terminimal/\">Terminimal</a></span><span class=\"copyright-theme-sep\">:: </span><a href=\"/rss.xml\">rss</a></div>"

# One of: blue, green, orange, pink, red.
# Defaults to blue. 
accent_color = "green"

# One of: blue, dark, green, orange, pink, red.
# Enabling dark background will also modify primary font color
# to be darker.
# Defaults to accent color (or, if not accent color specified, to blue). 
background_color = "dark"

menu_items = [
    # $BASE_URL is going to be substituted by base_url from configuration
    #{name = "blog", url = "$BASE_URL"},
        
    # # May be desired in future
    #{name = "archive", url = "$BASE_URL/localhost/archive"},

    {name = "about", url = "$BASE_URL/localhost/about"},

    {name = "publications", url = "$BASE_URL/localhost/publications"},
    
    {name = "tags", url = "$BASE_URL/localhost/tags"},

    {name = "source", url = "https://github.com/radical-subject/radicalsubject.github.io", newtab = true},
]

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# # The text shown at the bottom of a post,
# # before earlier/later post links.
# # Defaults to "Thanks for reading! Read other posts?"
# post_view_navigation_prompt = "Read more"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = true

favicon = "/coding_girl_128x128.png"
favicon_mimetype = "image/png"


# !!!!!! careful with using nginx + base_url. if u use nginx, base url should be / and links in menu items should be updated with /*host*/
# also for reloading of volume use 
# docker-compose down && docker volume rm movedradicalsubjectgithubio_vol && docker-compose up --build